version: '3'

services:
  nginx:
    restart: always
    container_name: capstone_nginx
    build:
      context: ./nginx
      dockerfile: DockerFile
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - backend

  redis:
    image: redis:alpine
    container_name: capstone_redis
    ports:
      - "6379:6379"

  database:
    restart: always
    container_name: capstone_mysql
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_DATABASE: capstone
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: 1234
      TZ: 'Asia/Seoul'
    ports:
      - "3306:3306"
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"

  backend:
    restart: always
    container_name: capstone_backend
    build:
      context: ./
      dockerfile: DockerFile
    ports:
      - "8080:8080"
    expose:
      - 8080
    environment:
      SPRING_DATASOURCE_driver-class-name: com.mysql.cj.jdbc.Driver
      SPRING_DATASOURCE_URL: jdbc:mysql://capstone-db.c4i1fa6mrqdu.ap-northeast-2.rds.amazonaws.com:3306/capstone?useSSL=false
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: pass2940
      SPRING_REDIS_HOST: redis
    depends_on:
      - database
      - redis