version: "3"

services:
  db:
    container_name: jeju-postgres
    restart: always
    build:
      context: "${DB_BUILD_CONTEXT}" # Dockerfile이 들어있는 경로 지정
      dockerfile: Dockerfile-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "${DB_USER_ID}"
      POSTGRES_PASSWORD: "${DB_USER_PASSWORD}"
      APP_DB_NAME: "${APP_DB_NAME}"
      APP_DB_USER: "${APP_DB_USER}"
      APP_DB_PASS: "${APP_DB_PASS}"
    volumes:
      - ${POSTGRES_HOME_DIR}/data:/var/lib/postgresql/data # ${POSTGRES_HOME_DIR}/data 부분이 실제 PostgreSQL 저장 경로로 컨테이너 종료 또는 삭제되었을 때 내부 데이터 날림 방지하기 위한 설정

  redis:
    image: redis:alpine
    command: redis-server --port 6379
    container_name: jeju-redis
    hostname: redis
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - 6379:6379
  
  # api:
  #   container_name: jeju-api
  #   restart: unless-stopped
  #   build:
  #     context: "${API_BUILD_CONTEXT}"
  #     dockerfile: Dockerfile-api
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
  #     - SPRING_DATASOURCE_USERNAME=postgres
  #     - SPRING_DATASOURCE_PASSWORD=postgres
  #     - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  #   depends_on:
  #     - db