version: '3'

networks:
  front-network:
    driver: bridge
  back-network:
    driver: bridge

services:
  nginx:
    restart: always
    container_name: capstone_nginx
    build:
      context: ./nginx
      dockerfile: DockerFile
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - backend
    networks:
      - front-network
      - back-network

  redis:
    image: redis:alpine
    container_name: capstone_redis
    ports:
      - "6379:6379"
    networks:
      - back-network

  database:
    restart: always
    container_name: capstone_mysql
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_DATABASE: capstone
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: 1234
      TZ: 'Asia/Seoul'
    networks:
      - back-network
    ports:
      - "3307:3307"
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"

  backend:
    restart: always
    container_name: capstone_backend
    build:
      context: ./
      dockerfile: DockerFile
    networks:
      - front-network
      - back-network
    ports:
      - "8080:8080"
    expose:
      - 8080
    environment:
      SPRING_DATASOURCE_driver-class-name: com.mysql.cj.jdbc.Driver
      SPRING_DATASOURCE_URL: jdbc:mysql://${RDS_ENDPOINT}:3306/capstone?useSSL=false
      SPRING_DATASOURCE_USERNAME: ${RDS_USER}
      SPRING_DATASOURCE_PASSWORD: ${RDS_PASSWORD}
      SPRING_REDIS_HOST: redis
    depends_on:
      - database
      - redis