FROM python:3.9

WORKDIR /app

ADD . /app

RUN apt-get update && apt-get install -y sudo
RUN apt-get install -y software-properties-common
RUN sudo add-apt-repository ppa:deadsnakes/ppa
RUN sudo apt-get install -y build-essential python3.9-dev
RUN pip install -r requirments.txt

CMD ["uwsgi","uwsgi.ini"]